[tasks.build]
run = "cargo build"

[tasks.install]
run = "cargo install --path ."

[tasks.format-clippy]
run = "cargo fmt && cargo clippy -- -D clippy::pedantic -D clippy::nursery"

[tasks.test]
run = "cargo test {{args}}"

[tasks.release]
run = "cargo release {{args}}"
